version: '3.8'

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: smartbus_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartbus_super
    ports:
      - '5432:5432'
    volumes:
      - smartbus_pgdata:/var/lib/postgresql/data

  # Interface visuelle PgAdmin (pour voir la base facilement)
  pgadmin:
    image: dpage/pgadmin4
    container_name: smartbus_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@smartbus.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres

  # Base de données de cache et files d'attente Redis (BullMQ)
  redis:
    image: redis:7-alpine
    container_name: smartbus_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - smartbus_redisdata:/data

volumes:
  smartbus_pgdata:
  smartbus_redisdata:
