export enum ModificationSource {
  WEB_ADMIN = 'WEB_ADMIN',
  MOBILE_PARENT = 'MOBILE_PARENT',
  DRIVER_TABLET = 'DRIVER_TABLET',
  SYSTEM_CRON = 'SYSTEM_CRON',
  API_EXTERNAL = 'API_EXTERNAL',
  MIGRATION_SCRIPT = 'MIGRATION_SCRIPT',
}
